[phases.setup]
nixPkgs = ["nodejs_20", "pnpm"]

[phases.install]
cmds = ["pnpm install"]

[phases.build]
cmds = ["pnpm --filter @jnj/types build && pnpm --filter @jnj/database build"]

[start]
cmd = "npx tsx apps/api/src/server.ts"
